Work on SVG
!!! DOES NOT WORK ANYMORE !!!

Because of this Grrrrrrrr !!!!

EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./SvgDrawingComponent class SvgDrawingComponent_Host - inline template:0:0
ORIGINAL EXCEPTION: ReferenceError: Snap is not defined
ORIGINAL STACKTRACE:
ReferenceError: Snap is not defined
    at new SVGGraphicContext (http://localhost:3000/app.js:29696:29)
    at new GraphicsEditor (http://localhost:3000/app.js:31231:35)
    at SvgDrawingComponent.ngAfterViewInit (http://localhost:3000/app.js:10790:32)
    at DebugAppView._View_SvgDrawingComponent_Host0.detectChangesInternal (SvgDrawingComponent.ngfactory.js:33:70)
    at DebugAppView.XDqp.AppView.detectChanges (http://localhost:3000/app.js:42764:14)
    at DebugAppView.XDqp.DebugAppView.detectChanges (http://localhost:3000/app.js:42870:44)
    at ViewRef_.detectChanges (http://localhost:3000/app.js:49517:65)
    at RouterOutlet.X/Y8.RouterOutlet.activate (http://localhost:3000/app.js:42112:42)
    at ActivateRoutes.VxOZ.ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/app.js:40325:16)
    at ActivateRoutes.VxOZ.ActivateRoutes.activateRoutes (http://localhost:3000/app.js:40302:22)
ERROR CONTEXT: